### ISSUE TITLE
network configuration and discovery

### ISSUE THREAD

**Issue by Vesperino** [aaasoft/Quick.Onvif#1]
Is this project have support for onvif network configuration for camera and discovery all cameras in network?

**Comment by aaasoft** [comment]
This project now is a wrapper of Onvif WebService invoke.
So it support network configuration,just use [OnvifClient.DeviceClient.GetNetworkInterfacesAsync] and [OnvifClient.DeviceClient.SetNetworkInterfacesAsync] method.
Discovery is not a Onvif WebService,so it not support now,maybe I will add this Discovery in the furture.

**Comment by Vesperino** [comment]
Thanks mate works!

**Comment by aaasoft** [comment]
> Is this project have support for onvif network configuration for camera and discovery all cameras in network?

Hi,you can use Onvif Discovery now.Try it:
https://www.nuget.org/packages/Quick.Onvif.Discovery
