### ISSUE TITLE
Search records

### ISSUE THREAD

**Issue by BertoMe** [aaasoft/Quick.Onvif#2]
Hello, how can I get all the recordings on the SD card of the recorder? Any sample?

https://www.onvif.org/ver10/recording.wsdl

**Comment by aaasoft** [comment]
> Hello, how can I get all the recordings on the SD card of the recorder? Any sample?
> 
> https://www.onvif.org/ver10/recording.wsdl

Hello, I just make a wrapper of Onvif WebService invoke.you should read document of Onvif or ask a question in StackOverflow.

**Comment by BertoMe** [comment]
Can I read recordings with your wrapper?
