### ISSUE TITLE
Read metadata from Metadata stream

### ISSUE THREAD

**Issue by ntdgo** [aaasoft/Quick.Onvif#3]
Hi,

Is there any solution to get Metadata stream from your code.

![image](https://github.com/aaasoft/Quick.Onvif/assets/37483861/60653755-e829-4005-9083-9ff0b3028fdd)

Thank you!

**Comment by aaasoft** [comment]
> The [ONVIF Streaming Specification](https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf) describes retrieving this via RTSP/RTP, as you would for a video or audio stream. I believe this is the only way.

[Refrence from https://github.com/quatanium/python-onvif/issues/67](https://github.com/quatanium/python-onvif/issues/67)
