### ISSUE TITLE
关于onvif库的用法

### ISSUE THREAD

**Issue by orcfnjmlns908** [aaasoft/Quick.Onvif#4]
请问该库支持语音文件转码和发送吗？我看了您的demo好像没有做这块的展示

**Comment by aaasoft** [comment]
你说的语音文件转码和发送是指什么？是文本转语音(TTS)，还是多媒体文件格式转换？这些都和Onvif协议无法的啊。TTS的话可以用Windows自带的TTS功能，多媒体文件格式转换的话可以用ffmpeg。
