### ISSUE TITLE
Memory Leak Observed When Using OnvifClient and MediaClient Connections

### ISSUE THREAD

**Issue by Vesperino** [aaasoft/Quick.Onvif#8]
I am experiencing a memory leak in my application when using OnvifClient along with MediaClient and Media2Client from the QuickNV.Onvif library. It appears that the OnvifClient does not implement IDisposable, which may be contributing to the issue. The memory leak is most noticeable when establishing new connections repeatedly, even though I attempt to close them using client.DeviceClient.CloseAsync() or client.DeviceClient.Abort().

Steps to Reproduce:

1. Create a new instance of OnvifClient for each connection to a camera.
2. Use MediaClient or Media2Client to perform operations.
3. After operations are complete, attempt to close the connection using client.DeviceClient.CloseAsync() or client.DeviceClient.Abort().
4. Repeat the process multiple times.
5. Observe memory usage increasing over time.

Code Sample:
```

public async Task<OnvifCameraDto> GetConfigurationForExistingCamera(string login, string password, string rtsp)
{
    var ip = ExtractIpFromRtsp(rtsp);
    var connection = await Connect(ip, login, password);

    OnvifCameraDto onvifCameraDto;

    try
    {
        onvifCameraDto = await GetConfigurationUsingMedia2Client(connection, ip);
    }
    catch (Exception ex)
    {
        Log.Error("Media2Client failed, falling back to MediaClient: " + ex.Message);
        onvifCameraDto = await GetConfigurationUsingMediaClient(connection, ip);
    }

    // Attempt to close the connection
    await connection.DeviceClient.CloseAsync();
    connection = null;

    return onvifCameraDto;
}
```
```
 private async Task<OnvifClient> Connect(string ip, string login, string password, int port = 80)
 {
     var client = new OnvifClient(
        new OnvifClientOptions
        {
            Host = ip,
            Port = port,
            UserName = login,
            Password = password
        });

     try
     {
         await client.ConnectAsync();
         return client;
     }
     catch (Exception ex)
     {
         throw new CustomException("Cannot connect to client", new List<string> { ex.Message }, statusCode: HttpStatusCode.NotAcceptable);
     }
 }
```
```
private async Task<OnvifRtspProfilesDto> GetRtspUrisForMainAndSubProfiles(string login, string password, string ip)
{
    var connection = await Connect(ip, login, password);

    OnvifRtspProfilesDto rtspProfiles;

    try
    {
        rtspProfiles = await GetRtspUrisUsingMedia2Client(connection);
    }
    catch (Exception ex)
    {
        rtspProfiles = await GetRtspUrisUsingMediaClient(connection);
    }

    // Attempt to close the connection
    await connection.DeviceClient.CloseAsync();
    connection = null;

    return rtspProfiles;
}
```
**Observed Behavior:**

- Memory usage increases with each new connection.
- Memory is not released after attempting to close connections using CloseAsync() or Abort().
- Over time, this leads to high memory consumption and potential application instability.

**Expected Behavior:**

- Memory used by connections should be properly released after closing them.
- Repeated connections should not cause cumulative memory growth.

**Additional Information:**

- MediaClient and Media2Client implement IDisposable, and I am using them within using statements to ensure proper disposal.
- OnvifClient does not implement IDisposable, and there is no straightforward way to dispose of it.
- The issue seems to originate from OnvifClient holding onto resources that are not being released.
- I observe the largest memory leaks when establishing new connections with OnvifClient, even after attempting to close them.

**Environment:**

- QuickNV.Onvif library version: 1.0.1
- .NET version: .net 8
- Operating System: Windows 11

**Attempts to Resolve:**

- Used client.DeviceClient.CloseAsync() and client.DeviceClient.Abort() to close connections.
- Ensured MediaClient and Media2Client are disposed properly using using statements.
- Removed calls to Abort() as suggested in some recommendations, but the issue persists.

**Possible Cause:**

- The lack of IDisposable implementation in OnvifClient might prevent proper resource cleanup.
- Persistent connections or unmanaged resources within OnvifClient are not being released.

**Request:**

Could you please investigate this issue?
Consider implementing IDisposable in OnvifClient to allow for proper disposal of resources.
Provide guidance on how to correctly manage the lifecycle of OnvifClient instances to prevent memory leaks.
Any suggestions or workarounds to mitigate this issue would be greatly appreciated.
Thank you for your assistance!

**Comment by aaasoft** [comment]
Thanks for your feedback @Vesperino. OnvifClient class now implement IDispose interface.You can try version 1.0.2 at [Nuget](https://www.nuget.org/packages/QuickNV.Onvif/1.0.2)
