### ISSUE TITLE
MessageSecurityException when connecting

### ISSUE THREAD

**Issue by StefH** [aaasoft/Quick.Onvif#9]
C# code:
``` csharp
var client = new QuickNV.Onvif.OnvifClient(new QuickNV.Onvif.OnvifClientOptions
{
  Host = "172.1.2.3",
  Port = 2000,
  UserName = "x",
  Password = "y"
});

await client.ConnectAsync();
```

Also using `ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Digest` or `ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Http` does not work.

Exception:
```
Unhandled exception. System.ServiceModel.Security.MessageSecurityException:
The HTTP request is unauthorized with client authentication scheme 'Digest'.
The authentication header received from the server was 'Basic realm="Onvif Basic Auth", Digest realm="Onvif Digest Auth", qop="auth",nonce="71a47afc39a0b524", opaque="", stale="false"'.
```

**Comment by aaasoft** [comment]
@StefH 
I think it's device's problem.I tested Hikvision and Dahua camera.It's OK to connect to.
Is the device has a public IPv4 or IPv6 address and can you provider user and password that I can have a test?

**Comment by StefH** [comment]
The camera is connected to local netwerk and the type is Avonic.

Connecting to this using other libraries like  
https://github.com/Jazea/Onvif.Core

Or

https://github.com/jimm98y/SharpOnvif


Does work correct.


Could it be that your Digest authentication implementation differs?

**Comment by aaasoft** [comment]
> The camera is connected to local netwerk and the type is Avonic.
> 
> Connecting to this using other libraries like https://github.com/Jazea/Onvif.Core
> 
> Or
> 
> https://github.com/jimm98y/SharpOnvif
> 
> Does work correct.
> 
> Could it be that your Digest authentication implementation differs?

@StefH That good,you can use other libraries to solve your problem.I don't have camera of this brand,so I can't test with it.Issue will close.
